---
- name: compliance check for STIG rules, packages, simplified
  hosts: all

  tasks:
  - name: "SCORED | 1.1.1.2 | PATCH | Remove freevxfs module"
    modprobe:
      name: freevxfs
      state: absent

  - name: "NOTSCORED | 1.2.5 | PATCH | Disable the rhnsd Daemon"
    service:
      name: rhnsd
      state: stopped
      enabled: no

  - name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
    service:
      name: crond
      enabled: yes
